---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:

  - name: ubuntu-12.04
    run_list:
    - recipe[apt]

  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[composer::default]
    attributes:
