---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  solo_rb:
    ssl_verify_mode: verify_peer

platforms:
  - name: ubuntu-14.04-chef-12
    run_list:
      - recipe[apt]
    driver:
      box: bento/ubuntu-14.04
    provisioner:
      require_chef_omnibus: 12
  - name: ubuntu-14.04-chef-13
    run_list:
      - recipe[apt]
    driver:
      box: bento/ubuntu-14.04
    provisioner:
      require_chef_omnibus: 13
  - name: ubuntu-16.04-chef-12
    run_list:
      - recipe[apt]
    driver:
      box: bento/ubuntu-16.04
    provisioner:
      require_chef_omnibus: 12
  - name: ubuntu-16.04-chef-13
    run_list:
      - recipe[apt]
    driver:
      box: bento/ubuntu-16.04
    provisioner:
      require_chef_omnibus: 13
  - name: centos-7.3-chef-12
    driver:
      box: bento/centos-7.3
    provisioner:
      require_chef_omnibus: 12
  - name: centos-7.3-chef-13
    driver:
      box: bento/centos-7.3
    provisioner:
      require_chef_omnibus: 13

suites:
  - name: default
    run_list:
      - recipe[composer::default]
    attributes: {
      "composer": {
        "install_globally": true
      }
    }
