addons:
  apt:
    sources:
      - chef-current-xenial
    packages:
      - chef-workstation

env:
  - CHEF_LICENSE=accept

services: docker

install: echo "skip bundle install"

before_script:
  - eval "$(chef shell-init bash)"
  - chef --version
  - chef exec berks install

script:
  - chef exec rake travis

branches:
  only:
    - master
    - /^release\/.*$/
    - /^feature\/.*$/
    - /^bugfix\/.*$/

notifications:
  email:
    - development@davidjoos.com
